name: e_commerce
description: "E-commerce app made in flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  dots_indicator: ^4.0.1
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_v2: ^6.4.0
  shared_preferences: ^2.5.5
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/data/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Roboto-Bold.ttf
          weight: 700